[package]
name = "ckb-dep-group-cache"
version = "0.100.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "The ckb rocksdb snapshot wrapper"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../types", version = "= 0.100.0-pre" }
im = "15.0.0"
